config/routes.rb
FeedbackLoop::Application.routes.draw do

  get "accesses/new"

	resources :users
	
	resources :sessions, only: [ :new, :create, :destroy ]

	resources :passwords, only: [ :new, :create ]

	resources :surveys do
		member do
			get 'begin'
			get 'results'
		end
	end

	resources :questions do
		member do
			get 'results'
		end
	end

	resources :surveys, only: [ :create, :new, :show, :edit, :update, :destroy ]

	resources :questions, only: [ :create, :new, :show, :edit, :update, :destroy ]

	resources :answers, only: [ :create, :new, :edit, :update ]

	resources :accesses, only: [ :create, :new ]

	root							to: 'info_pages#home'

	match '/help',				to: 'info_pages#help'
	match '/contact',			to: 'info_pages#contact'
	match '/end',				to: 'info_pages#end'
	
	match '/signup',			to: 'users#new'
	match '/user_surveys',	to: 'users#surveys'

	match '/signin',			to: 'sessions#new'
	match '/signout',			to: 'sessions#destroy', via: :delete

	match '/reset',			to: 'passwords#new'

end

app/models/question.rb
class Question < ActiveRecord::Base
	attr_accessible :title, :first_choice, :last_choice, :number_of_choices, :link
	belongs_to :survey
	has_many :answers, dependent: :destroy
	#has_many :users, through: :answers
	before_save :well_formed_uri

	validates :survey_id, presence: true
	validates :title, presence: true
	validates :first_choice, presence: true
	validates :last_choice,	presence: true
	validates :number_of_choices, numericality: {greater_than: 1, less_than_or_equal_to: MAX_CHOICES}


	default_scope order: 'questions.created_at'

	private
		def well_formed_uri
			self.link = ("http://" << self.link) if ! self.link.nil? and self.link.start_with?('www') 
		end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_filter :signed_in_user
	before_filter :survey_exists
	before_filter :correct_survey_of_question, only: [:destroy, :edit, :update, :show, :results]
	before_filter :not_anonymous_survey, only: :results

	def create
		@question = ApplicationController.current_survey.questions.build(params[:question])
		if @question.save
			flash[ :success ] = "Question created."
				
			redirect_to survey_url(ApplicationController.current_survey)
				
		else
			render 'new'
		end
	end
	
	def new
		@question = ApplicationController.current_survey.questions.build
	end

	def show
		@question = ApplicationController.current_survey.questions.find(params[:id])
		redirect_to(root_url, alert: "Can't find question with id #{params[:id]}! Default to home page") if @question.nil?

		#@answers = current_question.answers.paginate(page: params[:page])
	end

	def edit
		@question = ApplicationController.current_survey.questions.find(params[:id])
		redirect_to(root_url, alert: "Can't find question with id #{params[:id]}! Default to home page") if @question.nil?
	end

	def update
		@question = ApplicationController.current_survey.questions.find(params[:id])
		redirect_to(root_url, alert: "Can't find question with id #{params[:id]}! Default to home page") if @question.nil?
		
		if @question.update_attributes(params[:question])
			flash[:success] = "Question updated."
			
			redirect_to survey_url(ApplicationController.current_survey)
		else
			render 'edit'
		end
	end

	def destroy
		deleted_question = ApplicationController.current_survey.questions.find(params[:id])
		redirect_to(root_url, alert: "Can't find question with id #{params[:id]}! Default to home page") if deleted_question.nil?

		deleted_question.destroy
		flash[:success] = "Question deleted."

		if deleted_question.survey.questions.blank? && deleted_question.survey.available
			deleted_question.survey.available = false
			deleted_question.survey.save
			flash[:alert] = "This question was the last of the survey. As a result, the survey is not available for feedback anymore."
		end

		redirect_to survey_url(ApplicationController.current_survey)
	end

	def results
		@question = ApplicationController.current_survey.questions.find(params[:id])
		redirect_to(root_url, alert: "Can't find question with id #{params[:id]}! Default to home page") if @question.nil?
	end

	private

			def survey_exists
				redirect_to(root_url, alert: "No active survey! Default to home page") if ApplicationController.current_survey.nil?
			end

			def not_anonymous_survey
				survey = current_user.surveys.find_by_id(ApplicationController.current_survey)
				if survey.nil?
					redirect_to(root_url, alert: "Access prohibited! Default to home page") 
				else
					question = survey.questions.find_by_id(params[:id])
					redirect_to(root_url, alert: "Access prohibited! Default to home page") if question.survey.anonymous
				end
			end

			def correct_survey_of_question
				survey = current_user.surveys.find_by_id(ApplicationController.current_survey)
				if survey.nil?
					redirect_to(root_url, alert: "Access prohibited! Default to home page") 
				else
					question = survey.questions.find_by_id(params[:id])
					redirect_to(root_url, alert: "Access prohibited! Default to home page") if question.nil?
				end

				# ANOTHER METHOD BELOW A LITTLE BIT LESS SECURE
				#current_question= Question.find_by_id(params[:id])
				##if a survey with this id exist
				#if current_question
				#	survey = current_queston.survey
				#end
				#redirect_to(root_url) unless current_survey?(@user)
			end
end

app/helpers/questions_helper.rb
module QuestionsHelper

	def question_index(this_question)
		position = ApplicationController.current_survey.questions.index(this_question)

		if ! position
			redirect_to(root_url, alert: "Can't find position for question! Default to home page")
		else
			position
		end
	end


	def question_after?(this_question)
		position = ApplicationController.current_survey.questions.index(this_question)

		if ! position
			redirect_to(root_url, alert: "Can't find position for question! Default to home page")
		else
			if ( position + 1 ) >= ApplicationController.current_survey.questions.length
				false
			else
				ApplicationController.current_survey.questions[ position + 1]
			end
		end
	end

	def question_before?(this_question)
		position = ApplicationController.current_survey.questions.index(this_question)

		if ! position
			redirect_to(root_url, alert: "Can't find position for question! Default to home page")
		else
			if position.zero?
				false
			else
				ApplicationController.current_survey.questions[ position - 1]
			end
		end
	end

	def answer_path_for_question(this_question)
		if this_question
			answer_exist = Answer.where(user_id: current_user.id, question_id: this_question.id)

			ApplicationController.set_current_question(this_question)

			if answer_exist.first
				edit_answer_path(answer_exist.first, backward: false)
			else
				new_answer_path
			end
		else
			redirect_to(root_url, alert: "Can't find question! Default to home page")
		end
	end

	def answer_path_for_question_after(this_question)
		question = question_after?(this_question)

		if question
			answer_exist = Answer.where(user_id: current_user.id, question_id: question.id)

			ApplicationController.set_current_question(question)

			if answer_exist.first
				edit_answer_path(answer_exist.first, backward: false)
			else
				new_answer_path
			end
		else
			redirect_to(root_url, alert: "Can't find question! Default to home page")
		end
	end

	def answer_path_for_question_before(this_question)
		question = question_before?(this_question)

		if question
			answer_exist = Answer.where(user_id: current_user.id, question_id: question.id)

			if answer_exist.first
				edit_answer_path(answer_exist.first, backward: true)
			else
				redirect_to(root_url, alert: "Can't find answer with question id #{question_id}! Default to home page")
			end
		else
			redirect_to(root_url, alert: "Can't find question! Default to home page")
		end
	end

	def list_of_choices_for_question(this_question)
		list=[]
		for choice in (2..MAX_CHOICES) do
			pair = []
			pair.push choice.to_s
			pair.push choice
			list.push pair
		end

		return list
	end
end

app/views/questions/_choices.html.erb
<p>Possible choices :</p>
<p>1 : <%= question.first_choice %> </p>
<% if question.number_of_choices > 2 %>
	<p>
	<% for intermediate in (2..question.number_of_choices - 1) do %>
		<%= intermediate %>
		<% if intermediate < question.number_of_choices - 1 %>
			<%=','%>
		<% else %>
			<%= ': Intermediate choice(s)' %>
		<% end %>
	<% end %>
	</p>
<% end %>
<p><%= question.number_of_choices %> : <%= question.last_choice %>
<br /><br />

app/views/questions/_fields.html.erb
<%= f.label :title %>
<%= f.text_field :title %>

<div class="question_field">
	<p>
		<%= f.label :number_of_choices %>
		<span class="tips">This is the number of choices the surveyed has at disposal to answer the question e.g. '2' means that the surveyed will have only two choices to answer (usually, 'I agree' or 'I disagree').</span>
		<%= f.select :number_of_choices, options_for_select(list_of_choices_for_question(@question), @question.number_of_choices) %>
	</p>
</div>


<div class="question_field">
	<p>
		<%= f.label :first_choice, "Text for first choice" %>
		<span class="tips">These are the words that will be associated to the first choice in the list of choices.</span>
		<%= f.text_field :first_choice %>
	</p>
</div>

<div class="question_field">
	<p>
		<%= f.label :last_choice, "Text for last choice" %>
		<span class="tips">These are the words that will be associated to the last choice in the list of choices.</span>
		<%= f.text_field :last_choice %>
	</p>
</div>

<div class="question_field">
	<p>
		<%= f.label :link %>
		<span class="tips">This is an optional URI (ex-URL) to provide additional information to the surveyed. The URI must start with http://</span>
		<%= f.text_field :link %>
	</p>
</div>

app/views/questions/_question.html.erb
<li>
	<%= link_to question.title, question_path(question) %>

	| <%= link_to "edit", edit_question_path(question) %>

	| <%= link_to "delete", question, method: :delete, confirm: "This question will be deleted. Are you sure ?" %>

	<br />
</li>

app/views/questions/edit.html.erb
<%= provide(:title, "Update question") %> 
<h1>Update question</h1>

<%= render 'shared/error_messages', object: @question %>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@question) do |f| %>   

			<%= render 'fields', f: f %>

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/questions/new.html.erb
<%= provide(:title, 'New question') %>
<h1>New question</h1>

<%= render 'shared/error_messages', object: @question %>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@question) do |f| %>
		
			<%= render 'fields', f: f %>

			<%= f.submit "Create question", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/questions/results.html.erb
<% provide(:title, "Survey results") %> 
<h1><%= @question.survey.title %></h1>

<div class="row">
	<div class="span11 offset1">
		<h2 class="question_title"> <%= @question.title %> </h2>

		<% if @question.answers.any? %>
			<% @question.answers.each do |answer| %>
				<p>
					<div class="result_choice result_user_list">
						<%= answer.user.name %> 
					</div>
					
					<div class="result_answer result_user_list">
						<%= answer.choice.to_s %>
					</div>
				</p>

				<p>
					<% if ! answer.comment.nil? && ! answer.comment.blank? %>
						<div class="result_choice">
							comments : 
						</div>
					
						<div class="result_answer">
							<%= answer.comment %>
						</div>
					<% end %>
				</p>
				
				<div class="clear"><br /></div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/questions/show.html.erb
<% provide(:title, "Show question") %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for current_user %>
				<%= current_user.name %>
			</h1>
		</section>
	
	</aside>
	
	<div class="span8">
		<h1> <%= @question.title %> </h1>
		
		<%= render 'choices', question: @question %>

		<%= link_to 'Back to survey', survey_path(@question.survey) %>
	</div>
</div>