config/routes.rb
FeedbackLoop::Application.routes.draw do

  get "accesses/new"

	resources :users
	
	resources :sessions, only: [ :new, :create, :destroy ]

	resources :passwords, only: [ :new, :create ]

	resources :surveys do
		member do
			get 'begin'
			get 'results'
		end
	end

	resources :questions do
		member do
			get 'results'
		end
	end

	resources :surveys, only: [ :create, :new, :show, :edit, :update, :destroy ]

	resources :questions, only: [ :create, :new, :show, :edit, :update, :destroy ]

	resources :answers, only: [ :create, :new, :edit, :update ]

	resources :accesses, only: [ :create, :new ]

	root							to: 'info_pages#home'

	match '/help',				to: 'info_pages#help'
	match '/contact',			to: 'info_pages#contact'
	match '/end',				to: 'info_pages#end'
	
	match '/signup',			to: 'users#new'
	match '/user_surveys',	to: 'users#surveys'

	match '/signin',			to: 'sessions#new'
	match '/signout',			to: 'sessions#destroy', via: :delete

	match '/reset',			to: 'passwords#new'

end

app/controllers/info_pages_controller.rb
class InfoPagesController < ApplicationController
	def home
		if signed_in?
			non_private_surveys	= Survey.where(available: true, private: false)
			private_surveys 		= Survey.joins(:accesses).where(available: true, accesses: { user_id: current_user.id })

			merged_surveys = non_private_surveys.concat(private_surveys)
			merged_surveys.sort! {|x,y| y.created_at <=> x.created_at }
			@surveys = merged_surveys.paginate(page: 1, per_page: 30)
		end
	end

	def help
	end

	def contact
	end
end

app/helpers/info_pages_helper.rb
module InfoPagesHelper
end

app/views/info_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<div class="center hero-unit">
	<h2>
		Feedback Loop v3.1 by
		<% mail_sender = "Dear Punkware team, I want to let you know that ..." %> 

		<% if signed_in? %>
			<% mail_sender = mail_sender + "\n\nSincerely yours,\n\n" + current_user.name %>
		<% end %>

		<%= mail_to "punkware@free.fr", "Punkware", subject: "Regarding your Feedback Loop site...", body: mail_sender %>
		
		<br /><br />
		Found a bug ? Want a new functionality ? Tell us by clicking the link above. Thanks.
	</h2>
</div>

app/views/info_pages/end.html.erb
<% provide(:title, 'Give feedback') %>
<div class="center hero-unit">
	<h1> Thank you!</h1>
	
	<br />
	<%= link_to "Back to home page", root_path, class: "btn btn-large btn-primary" %>
</div>

app/views/info_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<div class="center hero-unit">
	<h2>
		What is Feedback Loop ?<br /><br /> 
		Feedback is a process in which information about the past or the present influences the same phenomenon in the present or future.<br /><br /> 
		Loop is the complete causal path that leads from the initial detection of the gap to the subsequent modification of the gap.<br /><br />
		Still not clear ? ;-) See below for more pragmatic information.
	</h2>
</div>

<h3>FOR SURVEY OWNER</h3>

<br />

<p>
	Create / Update / Edit / Delete survey
	<ul>
		<li>On the home page of Feedback Loop, use the “Manage my surveys” button. Then use the buttons and links provided to manage your surveys and questions.</li>
	</ul>
<p>

<p>
	Public / Private
	<ul>
		<li>If you set your survey as “public”, every user of Feedback Loop see it and are able to feedback it. But only you can see the results.</li>
		<li>If you set your surveys as “private”, you have to notify by email (using the “notify surveyed” button) the people you expect to feedback your survey. These people then have to join your private survey (see section “Joining a private survey” below) to feedback it. Only you can see the results.</li>
	</ul>
<p>

<p>
	Anonymous / Not anonymous
	<ul>
		<li>If you set your survey as anonymous, you are not able to see the names of the surveyed with their answers (i.e. you don’t know who has answered what). Surveyed are notified at the beginning of the feedback that the survey is anonymous.</li>
		<li>If you set your survey as not anonymous, you are able to see the names of the surveyed with their answers. Surveyed are notified at the beginning of the feedback that the survey is not anonymous. You cannot set a survey to “not anonymous” once it have some feedbacks (to comply with the commitment made first to the surveyed that the feedback is anonymous).</li>
	</ul>
</p>

<p>
	Available / Not available
	<ul>
		<li>If you set your survey as “available”, it is available to the surveyed. They can feedback it. You cannot set a survey to “available” if it has no questions.</li>
		<li>If you set your survey as “ not available”, it is not available to the surveyed. They cannot see it in any way. You usually set a survey to ‘not available’ at creation, when your are defining the questions, because the survey is at that time not ready for feedback, and at the end when you don’t want any more results (after you have operate the results, it is a good practice to delete the survey).</li>
	</ul>
</p>

<br />

<h3>FOR SURVEYED</h3>

<br />

<p>
	Feedback a survey
	<ul>
		<li>To feedback a survey, simply click on the survey name on the home page.</li>
		<li>You don’t have to answer all survey questions at one time. You can stop at any point (your answers are saved gradually) and continue later with the questions not answered.</li>
		<li>If you change your mind, you can start again the survey and change any of your saved answers.</li>
	</ul>
</p>

<p>
	Joining a private survey
	<ul>
		<li>If you receive a mail suggesting  you to join a private network, copy the survey code enclosed in the email, then go on the home  page of Feedback  Loop (sign up, or sign in beforehand if necessary) and use the “join private survey” button. Paste the code in the field and  “join”. Back to the home page, the private survey is now displayed and available for feedback.</li>
		<li>If you think the survey may interest other people you know, forward them the mail with the code. The code will work for them too.</li>
	</ul>
</p>

app/views/info_pages/home.html.erb
<% if ! signed_in? %>
	<% provide(:title, 'Home') %>
	<div class="center hero-unit">
		<h1>Feedback Loop</h1>
		<br />
		
		<h2>Surveys for everyone. By everyone.</h2>
		
		<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

		<p class="signin">Already have an account? <%= link_to "Sign in", signin_path %></p>
	</div>

	<%= link_to image_tag("rails.png", alt: "Rails") , 'http://rubyonrails.org/' %> Powered by Ruby on Rails
<% else %>
	<% provide(:title, 'All surveys') %>
	<div class="center hero-unit">
		<h1>Give Feedback!</h1>
	</div>
	<div class="row">
		<aside class="span4">
			<section>
				<h1>
					<%= gravatar_for @current_user %>
					<%= @current_user.name %>
				</h1>
			</section>
			<p><%= link_to "Manage my surveys", user_surveys_path, class: "btn btn-large btn-primary btn_width50" %></p>
			<p><%= link_to "Join private survey", new_access_path, class: "btn btn-large btn-primary btn_width50" %></p>
		</aside>
		
		<div class="span8">
			<% if @surveys.any? %>
				<h3><%=  pluralize(@surveys.count, "available survey")  %></h3>

				<p class="legend_line_home">
					Legend : 
					<span class="legend_item">
						<i class="icon-lock"></i> Private
					</span>

					<span class="legend_item">
						<i class="icon-eye-open"></i> NOT anonymous
					</span>
				</p>

				<ol class="survey_line">
					<% @surveys.each do |survey| %>
						<li>
							<span class="icons">
								<% if survey.private %>
									<i class="icon-lock"></i>
								<% end %>
							</span>

							<span class="icons">
								<% if ! survey.anonymous %>
									<i class="icon-eye-open"></i>
								<% end %>
							</span>
							
							<%= link_to survey.title, begin_survey_path(survey) %>
							
							<br />
							
							<span class="timestamp">
								Created <%= time_ago_in_words(survey.created_at) %> ago by <%= survey.user.name %>.
							</span>
						</li>
					<% end %>
				</ol>
				<%= will_paginate @surveys %>
			<% end %>
		</div>
	</div>
<% end %>