config/routes.rb
FeedbackLoop::Application.routes.draw do

  get "accesses/new"

	resources :users
	
	resources :sessions, only: [ :new, :create, :destroy ]

	resources :passwords, only: [ :new, :create ]

	resources :surveys do
		member do
			get 'begin'
			get 'results'
		end
	end

	resources :questions do
		member do
			get 'results'
		end
	end

	resources :surveys, only: [ :create, :new, :show, :edit, :update, :destroy ]

	resources :questions, only: [ :create, :new, :show, :edit, :update, :destroy ]

	resources :answers, only: [ :create, :new, :edit, :update ]

	resources :accesses, only: [ :create, :new ]

	root							to: 'info_pages#home'

	match '/help',				to: 'info_pages#help'
	match '/contact',			to: 'info_pages#contact'
	match '/end',				to: 'info_pages#end'
	
	match '/signup',			to: 'users#new'
	match '/user_surveys',	to: 'users#surveys'

	match '/signin',			to: 'sessions#new'
	match '/signout',			to: 'sessions#destroy', via: :delete

	match '/reset',			to: 'passwords#new'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
	attr_accessible :title, :anonymous, :private, :available, :link
	belongs_to :user
	has_many :questions, dependent: :destroy
	has_many :accesses, dependent: :destroy
	before_create :create_key
	before_save :well_formed_uri

	validates :user_id,	presence: true
	validates :title,		presence: true

	default_scope order: 'surveys.created_at DESC'

	private

		def create_key
			self.key = SecureRandom.urlsafe_base64
		end

		def well_formed_uri
			self.link = ("http://" << self.link) if ! self.link.nil? and self.link.start_with?('www') 
		end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	before_filter :signed_in_user
	before_filter :correct_user_of_survey,    only: [ :destroy, :edit, :update, :show, :results ]
	before_filter :feedbackable, only: [ :begin ]

	def create
		@survey = current_user.surveys.build(params[:survey])
		if @survey.save
			ApplicationController.set_current_survey(@survey)
			flash[ :success ] = "Survey created."
				
			redirect_to survey_url(ApplicationController.current_survey)
				
		else
			render 'new'
		end
	end
	
	def new
		@survey = current_user.surveys.build
		ApplicationController.set_current_survey(@survey)
	end

	def show
		@survey = current_user.surveys.find(params[:id])		
		ApplicationController.set_current_survey(@survey)

		redirect_to(root_url, alert: "Can't find survey with id #{params[:id]}! Default to home page") if @survey.nil?

		@questions = @survey.questions.paginate(page: params[:page])
	end

	def edit
		@survey = current_user.surveys.find(params[:id])
		ApplicationController.set_current_survey(@survey)

		redirect_to(root_url, alert: "Can't find survey with id #{params[:id]}! Default to home page") if @survey.nil?
	end

	def update
		@survey = current_user.surveys.find(params[:id])
		redirect_to(root_url, alert: "Can't find survey with id #{params[:id]}! Default to home page") if @survey.nil?

		# cannot make a survey available if it has no question
		if params[:survey][:available] == "1" and ! has_question?(@survey)
			flash[:error] = "Survey has been set back to unavailable because the survey has currently no associated question."
			params[:survey][:available] = "0"
		end

		# cannot make a survey not anonymous if it has answer
		if params[:survey][:anonymous] == "0" and has_answer?(@survey) and @survey.anonymous
			flash[:error] = "Survey has been set back to anonymous because the survey has some answers. It cannot be changed anymore."
			params[:survey][:anonymous] = "1"
		end
		
		if @survey.update_attributes(params[:survey])
			ApplicationController.set_current_survey(@survey)
			flash[:success] = "Survey updated."
			
			redirect_to user_surveys_url
		else
			render 'edit'
		end
	end

	def begin
		@survey = Survey.find(params[:id])
		ApplicationController.set_current_survey(@survey)
		redirect_to(root_url, alert: "Can't find survey with id #{params[:id]}! Default to home page") if @survey.nil?

		@questions = @survey.questions
		redirect_to(root_url, alert: "Can't find questions for survey with id #{params[:id]}! Default to home page") if @questions.nil?

	end

	def results
		@survey = current_user.surveys.find(params[:id])
		ApplicationController.set_current_survey(@survey)

		flash.now[:alert] = "The survey is still available to surveyed. The results may change at anytime." if @survey.available

		redirect_to(root_url, alert: "Can't find survey with id #{params[:id]}! Default to home page") if @survey.nil?
	end

	def destroy
		deleted_survey = current_user.surveys.find(params[:id])
		redirect_to(root_url, alert: "Can't find survey with id #{params[:id]}! Default to home page") if deleted_survey.nil?


		deleted_survey.destroy
		ApplicationController.set_current_survey(nil) if ApplicationController.current_survey?(deleted_survey)
		flash[:success] = "Survey deleted."
		redirect_to user_surveys_url
	end

	private

			def correct_user_of_survey
				survey = current_user.surveys.find_by_id(params[:id])
				redirect_to(root_url, alert: "Access prohibited! Default to home page") if survey.nil?

				# ANOTHER METHOD BELOW A LITTLE BIT LESS SECURE
				#current_survey = Survey.find_by_id(params[:id])
				##if a survey with this id exist
				#if current_survey
				#	@user = current_survey.user
				#end
				#redirect_to(root_url) unless current_user?(@user)
			end

			def feedbackable
				found = false

				feedback_survey = Survey.find_by_id(params[:id])

				if ! feedback_survey.nil?
					if has_question?(feedback_survey)
						non_private_surveys	= Survey.where(available: true, private: false)
						private_surveys 		= Survey.joins(:accesses).where(available: true, accesses: { user_id: current_user.id })

						merged_surveys = non_private_surveys.concat(private_surveys)
						if merged_surveys.find {|x| x.id == feedback_survey.id }
							found = true
						end
					end
				end
				redirect_to(root_url, alert: "Survey with id #{params[:id]} is not ready for feedback! Default to home page") if ! found
			end

end

app/helpers/surveys_helper.rb
module SurveysHelper
	def has_answer?(survey)
		questions=survey.questions
		if questions.blank?
			return false
		end

		questions.each do |question|
   		answers=question.answers
   		if answers.any?
   			return true
   		end
		end
		return false
	end

	def has_question?(survey)
		questions=survey.questions
		if questions.blank?
			return false
		else
			return true
		end
	end
end

app/views/surveys/_fields.html.erb
<%= f.label :title %>
<%= f.text_field :title %>

<div class="survey_field">
	<p>
		<%= f.label :anonymous %>
		<span class="tips">If checked, the surveyed will be anonymous:</span>
		<%= f.check_box :anonymous %>
	</p>
</div>


<div class="survey_field">
	<p>
		<%= f.label :private %>
		<span class="tips">If checked, selected surveyed are notified by email:</span>
		<%= f.check_box :private %>
	</p>
</div>

<% if ! creation %>
	<div class="survey_field">
		<p>
			<%= f.label :available %>
			<span class="tips">If checked, the survey is available to surveyed:</span>
			<%= f.check_box :available %>
		</p>
	</div>
<% end %>

<div class="survey_field">
	<p>
		<%= f.label :link %>
		<span class="tips">This is an optional URI (ex-URL) to provide additional information to the surveyed</span>
		<%= f.text_field :link %>
	</p>
</div>

app/views/surveys/_survey.html.erb
<li>
	<span class="icons">
		<% if survey.available %>
			<i class="icon-ok"></i>
		<% end %>
	</span>

	<span class="icons">
		<% if survey.private %>
			<i class="icon-lock"></i>
		<% end %>
	</span>

	<span class="icons">
		<% if ! survey.anonymous %>
			<i class="icon-eye-open"></i>
		<% end %>
	</span>

	<%= link_to survey.title, survey_path(survey) %>

	| <%= link_to "results", results_survey_path(survey) %>

	| <%= link_to "edit", edit_survey_path(survey) %>
	
	| <%= link_to "delete", survey, method: :delete, confirm: "This survey will be deleted. Are you sure ?" %>

	<br />
	
	<span class="timestamp">
		Created <%= time_ago_in_words(survey.created_at) %> ago.
	</span>
</li>

app/views/surveys/begin.html.erb
<% provide(:title, 'Give feedback') %>
<div class="center hero-unit">
	<h2> You're about to start the survey "<%= @survey.title %>"</h2>

	<% if @survey.anonymous %>
		<p> This survey is anonymous. <%= @survey.user.name %> will not be able to see your name. </p>
	<% else %>
		<p> This survey is NOT anonymous. <%= @survey.user.name %> will be able to see your name with your answers. </p>
	<% end %>

	<% if @survey.link.present? %>
		<p><%= link_to "Additional information about the survey available here.", @survey.link, target: "_blank" %></p>
	<% end %>
	
	<br />
	<%= link_to "Start survey !", answer_path_for_question(@survey.questions.first), class: "btn btn-large btn-primary" %>
</div>

app/views/surveys/edit.html.erb
<% provide(:title, "Update survey") %> 
<h1>Update survey</h1>

<%= render 'shared/error_messages', object: @survey %>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@survey) do |f| %>   

			<%= render 'fields', f: f, creation: false %>

			<br />

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/surveys/new.html.erb
<%= provide(:title, 'New survey') %>
<h1>New survey</h1>

<%= render 'shared/error_messages', object: @survey %>

<div class="row">
	<div class="span6 offset3">
			<%= form_for(@survey) do |f| %>
			
				<%= render 'fields', f: f, creation: true %>

				<%= f.submit "Create survey", class: "btn btn-large btn-primary" %>
			<% end %>
	</div>
</div>

app/views/surveys/results.html.erb
<% provide(:title, "Survey results") %> 
<h1><%= @survey.title %></h1>

<div class="row">
	<div class="span11 offset1">
		<% @survey.questions.each do |question| %>
	
			<h2 class="result_question_title"> <%= question.title %> </h2>

			<div class="result_question_details">
				<% if ! @survey.anonymous %>
					<%= link_to "See details", results_question_path(question) %>
				<% end %>
			</div>

			<div>
				<h5>1: <%= sanitize(question.first_choice) %> <i class="icon-arrow-right"></i> <%= question.number_of_choices %>: <%= sanitize(question.last_choice) %></h5>
			</div>

			<% comments = "" %>

			<% for choice in (1..question.number_of_choices) do %>
				<p>
					<div class="result_choice">
						<%= 'Choice ' << choice.to_s << ' : ' %>
					</div>
					
					<div class="result_answer">
						<%= pluralize(question.answers.where(choice: choice).count, "answer") %>
					</div>
				</p>

				<% if question.answers.where(choice: choice).any? %>
					<% question.answers.where(choice: choice).each do |answer| %>
						<% if ! answer.comment.nil? && ! answer.comment.blank? %>
							<% comments << '<div class="result_choice">Choice ' << choice.to_s << ' : </div>' %>
							<% comments << '<div class="result_answer">' << sanitize(answer.comment) << '</div>' %>
						<% end %>
					<% end %>
				<% end %>
			<% end %>

			<p>
				<div class="result_choice">
					<div class="result_bold">Count :</div>
				</div>
				
				<div class="result_answer">
					<%= pluralize(question.answers.count, "answer") %>
				</div>
			</p>

			<p>
				<div class="result_choice">
					<div class="result_bold">Average :</div> 
				</div>
				
				<div class="result_answer">
					<%= question.answers.average("choice")?question.answers.average("choice"):0 %>
				</div>
			</p>


			<p>
				<div class="result_choice result_bold">Comments :</div>
				<div class="result_answer">&nbsp;</div>
			</p>
			
			<p>
				<%=raw comments %>
			</p>
			<div class="clear"><br /></div>
		<% end %>
	</div>
</div>

app/views/surveys/show.html.erb
<% provide(:title, "Manage questions") %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for current_user %>
				<%= current_user.name %>
			</h1>
		</section>
		
		<p>
			<%= link_to "New question", new_question_path, class: "btn btn-large btn-primary btn_width50" %>
		</p>

		<% if ! @survey.available and @survey.questions.count > 0%>
			<p>
				<%= link_to "Make survey available", edit_survey_path(@survey), class: "btn btn-large btn-primary btn_width50", confirm: "Have you created all the questions for the survey ?" %>
			</p>
		<% end %>

		<% if @survey.available %>
			<p>
				<% mail_sender = "Hi!\n\nI\'ve just added a new survey titled \"" << @survey.title << "\" to Feedback Loop.\n" %> 

				<% if @survey.private %>
					<% mail_sender << "\nThis survey is private, to join it, click the \"Join private survey\" button on the home page and enter the key : " << @survey.key << "\n" %>
				<% end %>

				<% mail_sender << "\nSo just stop whatever you\'re doing and go to https://feedback-loop.herokuapp.com/ to feedback it.\n\nThanks!\n\n" << @survey.user.name %>

				<%= mail_to "", "Notify surveyed", subject: "A new survey is available on Feedback Loop", body: mail_sender, class: "btn btn-large btn-primary btn_width50" %>
			</p>
		<% end %>
	
	</aside>
	
	<div class="span8">
		<h1>Manage questions</h1>
		<h3>Questions for survey : <%= link_to @survey.title, user_surveys_path %> </h3>

		<% if @survey.questions.any? %>	
			<br />
			
			<ol class="questions">
				<%= render @questions %>
			</ol>
	
			<%= will_paginate @questions %>
		<% end %>
	</div>
</div>