config/routes.rb
FeedbackLoop::Application.routes.draw do

  get "accesses/new"

	resources :users
	
	resources :sessions, only: [ :new, :create, :destroy ]

	resources :passwords, only: [ :new, :create ]

	resources :surveys do
		member do
			get 'begin'
			get 'results'
		end
	end

	resources :questions do
		member do
			get 'results'
		end
	end

	resources :surveys, only: [ :create, :new, :show, :edit, :update, :destroy ]

	resources :questions, only: [ :create, :new, :show, :edit, :update, :destroy ]

	resources :answers, only: [ :create, :new, :edit, :update ]

	resources :accesses, only: [ :create, :new ]

	root							to: 'info_pages#home'

	match '/help',				to: 'info_pages#help'
	match '/contact',			to: 'info_pages#contact'
	match '/end',				to: 'info_pages#end'
	
	match '/signup',			to: 'users#new'
	match '/user_surveys',	to: 'users#surveys'

	match '/signin',			to: 'sessions#new'
	match '/signout',			to: 'sessions#destroy', via: :delete

	match '/reset',			to: 'passwords#new'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Help", help_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class= "navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Feedback Loop", root_path, id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					
					<% if signed_in? %>

						<% if is_admin? %>
							<li><%= link_to "Users", users_path %></li>
						<% end %>
					
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Update Profile", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
							</ul>
						</li>

					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>

				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title yield(:title) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
				
				<!-- or more cleaner code 
				<%= content_tag(:div, value, class: "alert alert-#{key}") %> -->
			<% end %>
			
			<%= yield %>	
			
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>